### ISSUE TITLE
[RadioGroup] Selected item does not remain selected after validation

### ISSUE THREAD

**Issue by ddoyen** [PremierLangage/components#12] opened 2019-09-17 16:44 UTC
The item selected in a RadioGroup component does not remain selected after the answer is submitted. It should be.

**Comment by mciissee** [comment] 2019-09-20 18:45
Can you give a link to an exercise with this behavior because the selected item should and is still selected after a submit on my side.

**Comment by ddoyen** [comment] 2019-09-20 18:58
https://pl.u-pem.fr/filebrowser/option?name=test_pl&path=Yggdrasil/template/radio.pl

**Comment by mciissee** [comment] 2019-09-20 19:11
I tested the component on Firefox 60.9.0esr 64 bits (the version installed for the desktops at the university), Chrome and Safari and the selection is persisted after the submit.

**Comment by mciissee** [comment] 2019-10-19 16:20
This issue cannot be reproduced so I will close it for now

**Closed by mciissee** 2019-10-19 16:20 UTC
